
#include "levels/classic.h"
#if 0
#include "levels/classic2.h"
#include "levels/childrenspack.h"
#include "levels/confusionpack.h"
#include "levels/panicpack.h"
#include "levels/twisterlevels.h"
#include "levels/varietypack.h"
#include "levels/variety2pack.h"
#include "levels/variety3pack.h"
#include "levels/variety4pack.h"
#include "levels/variety5pack.h"
#include "levels/variety6pack.h"
#include "levels/variety7pack.h"
#include "levels/variety8pack.h"
#include "levels/variety9pack.h"
#include "levels/variety10pack.h"
#include "levels/variety11pack.h"
#include "levels/variety12pack.h"
#endif
